# Let's use our custom image with doppler pre-installed
image:
  file: .gitpod.Dockerfile

# Let's install our VSCode Extensions
vscode: 
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliermarsh.ruff

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: OpenAPI /docs
    command: doppler setup --no-interactive && gp ports await 8000 && gp preview $(gp url 8000)/docs
  - name: Open ngrok connection
    command: doppler setup --no-interactive && doppler run --mount /home/gitpod/.config/ngrok/ngrok.yml --mount-template ngrok.yaml -- ngrok start fastapi-openid-connect
  - init: pip install -r requirements.txt # runs during prebuild
    command: doppler setup --no-interactive && doppler run --mount ../client_secret.json --mount-template oauth2_client_secret.json  -- doppler run --mount-template jwks_secret --mount ../jwks_secret -- doppler run -- uvicorn main:app --reload
