# Let's use our custom image with doppler pre-installed
image:
  file: .gitpod.Dockerfile

# Let's install our VSCode Extensions
vscode: 
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliermarsh.ruff

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: OpenAPI /docs
    command: gp ports await 8000 && gp preview $(gp url 8000)/docs
  - init: pip install -r requirements.txt # runs during prebuild
    command: doppler run -p fastapi-openid-connect-playground -c dev -- uvicorn main:app --reload