# Let's use our custom image with doppler pre-installed
image:
  file: .gitpod.Dockerfile

# Let's install our VSCode Extensions
vscode: 
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliermarsh.ruff

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: OpenAPI /docs
    command: doppler setup --no-interactive && gp ports await 8000 && gp preview $(gp url 8000)/docs
  - name: Open ngrok connection
    command: doppler setup --no-interactive && doppler secrets -p fastapi-openid-connect-playground -c dev substitute ngrok.yaml > /home/gitpod/.config/ngrok/ngrok.yml && ngrok start fastapi-openid-connect
  - init: pip install -r requirements.txt # runs during prebuild
    command: doppler setup --no-interactive && doppler secrets -p fastapi-openid-connect-playground -c dev substitute oauth2_client_secret.json > ../client_secret.json && doppler secrets -p fastapi-openid-connect-playground -c dev substitute jwks_secret > ../jwks_secret && doppler run -p fastapi-openid-connect-playground -c dev -- uvicorn main:app --reload
