name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ $ACTIONS_ID_TOKEN_REQUEST_URL"
      - run: echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
      - name: curl our endpoint
        run: |
          curl -H "Accept: application/json; api-version=2.0"  https://fastapi-openid-connect.ngrok.io/read-jwt-token -H "Content-Type: application/json" -d "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
      - run: echo "$ACTIONS_RUNTIME_TOKEN"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Get-Token:
    environment: Production
    runs-on: ubuntu-latest
    steps:
    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          const request = require('request')
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)
          request.post({
            url: "https://fastapi-openid-connect.ngrok.io/read-jwt-token",
            headers: {
              "Content-Type": "application/json"
            },
            json: id_token
          }, function (error, response, body) {
            console.log(response)
          })